# Dependency Review Action
#
# This Action will scan dependency manifest files, and upload the information to the dependency graph.
# Furthermore, it will scan changes in manifest files on a PR and add information on those changes to the PR.
#
name: 'Dependency management'
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a specific version, e.g., '3.9', '3.10', '3.11', '3.12'
      - name: 'Install pip-tools'
        run: pip install pip-tools
      - name: 'Generate requirements.txt from requirements.in'
        run: pip-compile requirements.in
      - name: 'Component Detection dependency submission action'
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.6
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        # only run the dependency review action on pull requests
        if: github.event_name == 'pull_request'
        with:
          comment-summary-in-pr: always
          fail-on-severity: moderate
          deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
          retry-on-snapshot-warnings: true